### ISSUE TITLE
PubSub API

### ISSUE THREAD

**Issue by fawind** [fawind/mongochain#5]
**Goal:** Generic API for sending and receiving messages using PubSub. Messages are serialized objects.

**Tasks:**

- [ ] Method to broadcast message to topic.
- [ ] Method to subscribe to topic.
    * Should accept a callback function as parameter which gets invoked on incoming messages.
- [ ] Object serialization and deserialization for messages.
